os:
  - linux

language: cpp

# use newer Trusty images
sudo: required
dist: precise

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
        source:
          - ubuntu-toolchains-r-test
        packages:
          - gcc-4.9
          - g++-4.9
        env: CC=gcc-4.9 CXX=g++-4.9
    - compiler: gcc
      addons:
        apt:
        source:
          - ubuntu-toolchains-r-test
        packages:
          - gcc-5
          - g++-5
        env: CC=gcc-5 CXX=g++-5
    - compiler: clang
      addons:
        apt:
        source:
          - ubuntu-toolchains-r-test
          - llvm-toolchain-precise-3.8
        packages:
          - clang-3.8
        env: CC=clang-3.8 CXX=clang-3.8

before_install:
  - sudo apt-get update -qq

env:
  native:
    - CROSS_COMPILE32=0
    - BUNDLED_LIBS=1
    - BUNDLED_SDL=1
    - BUNDLED_ZLIB=1
    - BUNDLED_MINIZIP=1
    - BUNDLED_JPEG=1
    - BUNDLED_LUA=1
    - BUNDLED_OGG=1

before_script:
  - ./misc/travis-setup.sh

script:
  - CC=${CC} CXX=${CCX} ./easybuild.sh

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#etlegacy"
    use_notice: true
    skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5a93d4b59447e6129a58
    on_success: change
    on_failure: always
    on_start: never
